export DERIVE_KEY=derivekey
export DECRYPT_FILE=decryptfile
export ENCRYPT_FILE=encryptfile
export LEDGER_DECRYPT_FILE=decryptfile-with-ledger
export LEDGER_ENCRYPT_FILE=encryptfile-with-ledger
export LEDGER_DECRYPT_ALL_FILES=decrypt-all-ledger-files
export SECURE_DELETE=secure-delete
export SANITIZE_CLI_HISTORY=sanitize-cli-history
